pipeline { 
    agent any 
    stages { 
        stage('Clone Repo') { 
            steps { 
                git 'https://github.com/Aditya-T3/portfolio-app.git' 
            } 
        } 
 
        stage('Build Docker Image') { 
            steps { 
                script { 
                    docker.build("portfolio-app") 
                } 
            } 
        } 
 
        stage('Run Container') { 
            steps { 
                script { 
                    docker.image("portfolio-app").run("-d -p 8080:80") 
                } 
            } 
        } 
    } 
}